config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'home/index'
  resources :reports do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :report
end

app/models/report.rb
class Report < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :comments
  enum :role, [:normal_user, :author, :admin]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authorize_request(kind=nil)
        unless kind.include?(current_user.role)
            redirect_to reports_path, notice: 'You are not authorized to perform this action'
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_report
  before_action :authenticate_user!, except: %i[ index show]
  before_action :comment_permission, only: %i[ edit destroy ]
  before_action only: %i[ destroy ] do
    authorize_request(["admin"])
  end
  
  # GET /comments or /comments.json
  def index
    @comments = @report.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @report.comments.new
    
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @report.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to report_comment_path(@report.id, @comment.id), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to report_comment_path(@report.id, @comment.id), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to report_comments_path(@report.id), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_report
      @report = Report.find(params[:report_id])
    end

    def comment_permission
      unless @comment.user_id == current_user.id || current_user.role != 2
        redirect_to report_comment_path(@report.id), notice: 'You are not allowed to perform this action'
      end
    end     
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show]
  before_action only: %i[new create destroy edit] do
    authorize_request(["admin"])
  end 
  #before_action :authenticate_user!, except: %i[ index show]
  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to report_url(@report), notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to report_url(@report), notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Report:</strong>
    <%= comment.report_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@report,comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <strong><%= current_user.email %></strong>
  </div>

  <div>
    <%= form.label :report_id, style: "display: block" %>
    <strong><%= @report.id %></strong>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", report_comment_path(@report.id, @comment.id) %> |
  <%= link_to "Back to comments", report_comment_path(@report.id) %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", report_comment_path(@report.id, comment.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_report_comment_path(@report.id) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", report_comments_path(@report.id) %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Back to comments", report_comments_path(@report.id) %>
    <% if @comment.user_id == current_user.id || current_user.role == 2 %>
      |<%= link_to "Edit this comment", edit_report_comment_path(@report.id, @comment.id) %>|
      <%= button_to "Destroy this comment", report_comment_path(@report.id, @comment.id), method: :delete %>
    <% end %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheRealNews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>

  <body>
  <%= render "shared/navbar" %>
  <div class="container" >
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
  
  </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div id="<%= dom_id report %>">
  <p>
    <strong>Title:</strong>
    <%= report.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= report.description %>
  </p>

  <p>
    <strong>Image:</strong>
   <%= image_tag report.image, alt: "Image news" %>
  </p>

</div>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Show this report", @report %> |
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reports</h1>

<div id="reports">
  <% @reports.each do |report| %>
    <%= render report %>
    <p>
      <%= link_to "Show this report", report %>
    </p>
  <% end %>
</div>
<% if user_signed_in? %>
      <% if current_user.role == 2  %>  
        <%= link_to "New report", new_report_path %>
    <% end %>
<% end %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @report %>

<div>
    <% if user_signed_in? %>
      <% if current_user.role == "admin"  %>  
        <%= link_to "Edit this report", edit_report_path(@report) %> |
        <%= button_to "Destroy this report", @report, method: :delete %>
      <% end %>
    <% end %>
    
  <%= link_to "Back to reports", reports_path %> | <%= link_to "New comment", new_report_comment_path(@report.id) %>
  | <%= link_to "Comments", report_comments_path(@report.id) %>
  
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark " data-bs-theme="dark" >
  <div class="container">
    <%= link_to "The Rial News", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ms-auto" >
    <li><%= link_to "News", reports_path , class:"nav-link"  %></li>
    </ul>
      <ul class="navbar-nav ms-auto">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? %>
            <% if current_user.email %>
            Hola <%= current_user.email %>
            <% end %>
            <% else %>
            Inicia Sesión o Regístrate
            <% end %>
          </a>
          <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
            <% else %>
            <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>